DEBUG = True
SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/test.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = 'seckey'
FANFOU_CONSUMER_KEY = ''
FANFOU_CONSUMER_SECRET = ''
FANFOU_AUTH_KEY = ''
FANFOU_AUTH_SECRET = ''
